config/routes.rb
Rails.application.routes.draw do
  get 'show_individual/index'
  get 'show_element/show'
  get 'home/index'
  
  root to: 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/show_element_controller.rb
class ShowElementController < ApplicationController

  require 'json'

  before_action :set_elements, only: [:show]

  def show


    @element = {at_num: @elements["elements"][params[:element].to_i - 1]["number"], 
                symbol: @elements["elements"][params[:element].to_i - 1]["symbol"], 
                name: @elements["elements"][params[:element].to_i - 1]["name"], 
                number: @elements["elements"][params[:element].to_i - 1]["atomic_mass"],
                discovery_id: @elements["elements"][params[:element].to_i - 1]["discovery_id"],
                named_id: @elements["elements"][params[:element].to_i - 1]["named_id"]
                }
    
    @information = {
      category: @elements["elements"][params[:element].to_i - 1]["category"],
      utility_img: @elements["elements"][params[:element].to_i - 1]["utility_img"],
      get_image: @elements["elements"][params[:element].to_i - 1]["get_img"],
      summary: @elements["elements"][params[:element].to_i - 1]["summary"],
      discovered_by: @elements["elements"][params[:element].to_i - 1]["discovered_by"] ? @elements["elements"][params[:element].to_i - 1]["discovered_by"] : 'desconhecido',
      how_produce: @elements["elements"][params[:element].to_i - 1]["how_produce"],
      named_by: @elements["elements"][params[:element].to_i - 1]["named_by"] ? @elements["elements"][params[:element].to_i - 1]["named_by"] : @elements["elements"][params[:element].to_i - 1]["discovered_by"] ? @elements["elements"][params[:element].to_i - 1]["discovered_by"] : 'desconhecido',
      phase: @elements["elements"][params[:element].to_i - 1]["phase"],
      utility: @elements["elements"][params[:element].to_i - 1]["utility"],
      spectral_img: @elements["elements"][params[:element].to_i - 1]["spectral_img"],
      discovery_img: @elements["elements"][params[:element].to_i - 1]["discovery_img"],
      named_img: @elements["elements"][params[:element].to_i - 1]["named_img"] ? @elements["elements"][params[:element].to_i - 1]["named_img"] : @elements["elements"][params[:element].to_i - 1]["discovery_img"] ? @elements["elements"][params[:element].to_i - 1]["discovery_img"] : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTBLzQlz0M52leMvfZRWPldnWElju72nM0aNO9c4CAkejrAOpPg",
    }
    
    @properties = {
      density: @elements["elements"][params[:element].to_i - 1]["density"],
      boil: @elements["elements"][params[:element].to_i - 1]["boil"],
      atomic_mass: @elements["elements"][params[:element].to_i - 1]["atomic_mass"],
      melt: @elements["elements"][params[:element].to_i - 1]["melt"],
      molar_helt: @elements["elements"][params[:element].to_i - 1]["molar_heat"],
      electron_configuration: @elements["elements"][params[:element].to_i - 1]["electron_configuration"],
		  electron_affinity: @elements["elements"][params[:element].to_i - 1]["electron_affinity"],
		  electronegativity_pauling: @elements["elements"][params[:element].to_i - 1]["electronegativity_pauling"],
      color_name: "transparent",
      quote: @elements["elements"][params[:element].to_i - 1]["source"],
      hex_color: "#ffffff",
    }
  end

  def set_elements
    
    @elements = JSON.parse(File.read('app/assets/javascripts/periodicTable.json'))
    
  end
end

app/helpers/show_element_helper.rb
module ShowElementHelper
end

app/views/show_element/_carousel.html.erb
<div id="carouselElement" class="carousel slide" data-ride="carousel">

  <div class="carousel-inner">
     
    <div class="carousel-item active">
      <img src="<%=@information[:named_img]%>" alt="<%=@information[:named_by] != nil ? @information[:named_by] : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRBowkIcqJfj8kmmcKirc6axLEyq5gAyL_aDgad1FZ9QCTG6IaI" %>" class="card-img-top h-25">
          <div class="carousel-caption d-none d-md-block">
            <h5>Nomeado por</h5>
            <p><%=@information[:named_by]%></p>
          </div>
    </div>
    <div class="carousel-item">
      <img src="<%=@information[:discovery_img]%>" alt="<%=@information[:discovered_by] != nil ? @information[:discovered_by] : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRBowkIcqJfj8kmmcKirc6axLEyq5gAyL_aDgad1FZ9QCTG6IaI" %>" class="card-img-top h-25">
          <div class="carousel-caption d-none d-md-block">
            <h5>Descoberto por</h5>
            <p><%=@information[:discovered_by]%></p>
          </div>
    </div>
    
  </div>
  
  <a class="carousel-control-prev" href="#carouselElement" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a> <a class="carousel-control-next" href="#carouselElement" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/show_element/_content.html.erb
<div class="jumbotron mt-5 " style= "background-color: #ffffff30;">
  <h1 class="display-4"><%=@element[:name]%></h1>
  <p class="lead"><%=@information[:summary]%></p>
  <hr class="my-4">
  <p>Categoria: <%=@information[:category]%></p>
  <a class="btn btn-primary btn-lg" href="<%= %>" role="button">Leia mais</a>
</div>

<%= link_to 'Back', onclick: "window.history.back()" %>

<div class="card mt-5 shadow-lg">
    
    <h1 class="card-title ml-5 mt-5">Sobre</h1>
    
    <div class="card-body">

        <div class="row">

            <div class="col-lg-4 text-center mt-5">
                
                <h4 class="text-dark">Utilidade</h4>
                
                <div class="justify-content-center align-items-center mt-5" >
                    <div class="card shadow-lg">
                        <img class="card-img-top" src="<%=@information[:utility_img]%>" alt="Card image cap">
                        <div class="card-body bg-">
                           
                            <p class="card-text mt-3"><%=@information[:utility]%></p>
                            
                            <a class="btn btn-primary btn-lg" href="<%= %>" role="button">Leia mais</a>
                            
                        </div>
                    </div>
                </div>
            </div>
            
            <div class="col-lg-4 text-center mt-5">
                <h4 class="text-dark">Onde encontramos</h4>
                <div class="justify-content-center align-items-center mt-5">
                    <div class="card shadow-lg">
                        <img class="card-img-top" src="<%=@information[:get_image]%>" alt="Card image cap">
                        <div class="card-body">
                            
                            <p class="card-text mt-3"><%=@information[:how_produce]%></p>
                            <a class="btn btn-primary btn-lg" href="<%= %>" role="button">Leia mais</a>
                        </div>
                    </div>
                </div>
            </div>
            
            <div class="col-lg-4 text-center mt-5">
                
                <h4 class="text-dark">Quem descobriu</h4>
            
                <div class="justify-content-center align-items-center mt-5">
                    <div class="card shadow-lg">
                        <%= render "carousel"%>
                        <div class="card-body">
                            <p class="card-text mt-3">Descoberto por: <strong><%=@information[:discovered_by]%></strong></p>
                            <%= link_to "Leia mais", show_individual_index_path(discovery_by: @element[:discovery_id]), {class: "btn btn-primary btn-lg", role: "button", onclick: "restoreExecuted()" }%>
                            <p class="card-text mt-3">Nomeado por: <strong><%=@information[:named_by]%></strong></p>
                            <%= link_to "Leia mais", show_individual_index_path(named_by: @element[:named_id]), {class: "btn btn-primary btn-lg", role: "button", onclick: "restoreExecuted()" }%>
                        </div>
                    </div>
                </div>
                
            </div>
            
        </div>
        
    </div>
    
</div>


<div class="card mt-5 shadow">
    
    <h1 class="card-title ml-5 mt-5">Propriedades</h1>
    
    <div class="card-body">
        
        <div class="row mt-5 justify-content-center align-items-center p-3">
            
            <div class="col-12 justify-content-center align-items-center p-3 border-0">
                <%= render "properties" %>
            </div>
        </div>
        
    </div>
    
</div>

app/views/show_element/_footer.html.erb
<footer class="page-footer font-small bg-dark mt-5 p-3 mb-5">

    <!-- Footer Links -->
    <div class="container-fluid text-center text-md-left">

      <!-- Grid row -->
      <div class="row">

        <!-- Grid column -->
        <div class="col-md-6 mt-md-0 mt-3">

          <!-- Content -->
          <h5 class="text-uppercase text-white">Descubra mais</h5>
          <p class="text-white">Here you can use rows and columns here to organize your footer content.</p>

        </div>
        <!-- Grid column -->

        <hr class="clearfix w-100 d-md-none pb-3">

        <!-- Grid column -->
        <div class="col-md-3 mb-md-0 mb-3">

            <!-- Links -->
            <h5 class="text-uppercase text-white">Links</h5>

            <ul class="list-unstyled">
              <li>
                <a href="#!">Link 1</a>
              </li>
              <li>
                <a href="#!">Link 2</a>
              </li>
              <li>
                <a href="#!">Link 3</a>
              </li>
              <li>
                <a href="#!">Link 4</a>
              </li>
            </ul>

          </div>
          <!-- Grid column -->

          <!-- Grid column -->
          <div class="col-md-3 mb-md-0 mb-3">

            <!-- Links -->
            <h5 class="text-uppercase text-white">Links</h5>

            <ul class="list-unstyled">
              <li>
                <a href="#!">Link 1</a>
              </li>
              <li>
                <a href="#!">Link 2</a>
              </li>
              <li>
                <a href="#!">Link 3</a>
              </li>
              <li>
                <a href="#!">Link 4</a>
              </li>
            </ul>

          </div>
          <!-- Grid column -->

      </div>
      <!-- Grid row -->

    </div>
    <!-- Footer Links -->

    <!-- Copyright -->
    <div class="footer-copyright text-center py-3 text-white">2019, Desenvolvido por:
      <a href="https://mdbootstrap.com/education/bootstrap/" class="text-white"> Miller César de Oliveira</a>
    </div>
    <!-- Copyright -->

</footer>

app/views/show_element/_header.html.erb
<div class="pos-f-t">
  <div class="collapse" id="navbarToggleExternalContent">
    <div class="bg-dark p-4">
      <h5 class="text-white h4"><%= @element[:name] %></h5>
      <%= link_to "Voltar", home_index_path, {class:"text-muted"} %>
    </div>
  </div>
  <nav class="navbar navbar-dark bg-dark">
    <button class="navbar-toggler" type="button" data-toggle="dropdown" data-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </nav>
</div>

app/views/show_element/_properties.html.erb
<div class= "row">
    <div class ="col-lg-4 col-sm-12 p-2">
        <div class="card shadow-lg">
            <img class="card-img-top" src="https://www.grupoescolar.com/galeria/fotos/F07AB72CA.jpg" alt="Card image cap">
            <div class="card-body">
              <h5 class="card-title">Densidade</h5>
              <p class="card-text"><%= @properties[:density] %></p>
              <a href="<%=@properties[:quote]%>" class="card-text"><small class="text-muted">Fonte:<%=@properties[:quote]%> </small></a>
            </div>
        </div>
    </div>
    
    <div class ="col-lg-4 col-sm-12 p-2">
        <div class="card shadow-lg">
            <img class="card-img-top" src="https://mundoeducacao.bol.uol.com.br/upload/conteudo_legenda/38fdc6bcb1c0f2d16fd8983e35487c4a.jpg" alt="Card image cap">
            <div class="card-body">
              <h5 class="card-title">Ponto ebulição</h5>
              <p class="card-text"><%= @properties[:boil] %> K</p>
              <a href="<%=@properties[:quote]%>" class="card-text"><small class="text-muted">Fonte:<%=@properties[:quote]%> </small></a>
            </div>
        </div>
    </div>
    
    <div class ="col-lg-4 col-sm-12 p-2">
        <div class="card shadow-lg">
            <img class="card-img-top" src="https://www.resumoescolar.com.br/wp-content/imagens/massa-atomica-e-molecular.jpg" alt="Card image cap">
            <div class="card-body">
              <h5 class="card-title">Massa Atômica</h5>
              <p class="card-text"><%=@properties[:atomic_mass]%></p>
              <a href="<%=@properties[:quote]%>" class="card-text"><small class="text-muted">Fonte:<%=@properties[:quote]%> </small></a>
            </div>
        </div>
    </div>
</div>

<div class= "row mt-5">
    <div class ="col-lg-4 col-sm-12 p-2">
        <div class="card shadow-lg">
            <img class="card-img-top" src="https://static.todamateria.com.br/upload/ge/lo/gelofusao.jpg" alt="Card image cap">
            <div class="card-body">
              <h5 class="card-title">Ponto de fusão</h5>
              <p class="card-text"><%=@properties[:melt]%> K</p>
              <a href="<%=@properties[:quote]%>" class="card-text"><small class="text-muted">Fonte:<%=@properties[:quote]%> </small></a>
            </div>
        </div>
    </div>

    <div class ="col-lg-4 col-sm-12 p-2">
        <div class="card shadow-lg">
            <img class="card-img-top" src="https://abrilguiadoestudante.files.wordpress.com/2016/08/screenshot_66.png?w=337&h=343" alt="Card image cap">
            <div class="card-body">
              <h5 class="card-title">Calor molar</h5>
              <p class="card-text"><%=@properties[:molar_helt]%></p>
              <a href="<%=@properties[:quote]%>" class="card-text"><small class="text-muted">Fonte:<%=@properties[:quote]%> </small></a>
            </div>
        </div>
    </div>
    
    <div class ="col-lg-4 col-sm-12 p-2">
        <div class="card shadow-lg">
            <img class="card-img-top" src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Electron_orbitals.svg/500px-Electron_orbitals.svg.png" alt="Card image cap">
            <div class="card-body">
              <h5 class="card-title">Configuração eletrônica</h5>
              <p class="card-text"><%=@properties[:electron_configuration]%></p>
              <a href="<%=@properties[:quote]%>" class="card-text"><small class="text-muted">Fonte:<%=@properties[:quote]%> </small></a>
            </div>
        </div>
    </div>
</div>

<div class= "row mt-5">
    <div class ="col-lg-4 col-sm-12 p-2">
        <div class="card shadow-lg">
            <img class="card-img-top" src="https://s1.static.brasilescola.uol.com.br/artigos/ao-receber-um-eletron-atomo-libera-uma-quantidade-energia-determinada-pela-eletroafinidade-1319203371.jpg?i=https://brasilescola.uol.com.br/upload/conteudo/images/ao-receber-um-eletron-atomo-libera-uma-quantidade-energia-determinada-pela-eletroafinidade-1319203371.jpg" alt="Card image cap">
            <div class="card-body">
              <h5 class="card-title">Afinidade eletronica</h5>
              <p class="card-text"><%=@properties[:electron_affinity]%></p>
              <a href="<%=@properties[:quote]%>" class="card-text"><small class="text-muted">Fonte:<%=@properties[:quote]%> </small></a>
            </div>
        </div>
    </div>

    <div class ="col-lg-4 col-sm-12 p-2">
        <div class="card shadow-lg">
            <img class="card-img-top" src="https://mundoeducacao.bol.uol.com.br/upload/conteudo/eletronegatividade.png" alt="Card image cap">
            <div class="card-body">
              <h5 class="card-title">Eletronegatividade de Pauling</h5>
              <p class="card-text"><%=@properties[:electronegativity_pauling]%></p>
              <a href="<%=@properties[:quote]%>" class="card-text"><small class="text-muted">Fonte:<%=@properties[:quote]%> </small></a>
            </div>
        </div>
    </div>
</div>

app/views/show_element/show.html.erb
<div class="container-fluid justify-content-center" id="main">
    <%= render "header" %>
    <%= render "content" %>
    <%= render "footer" %>
</div>